services:
  postgres:
    image: postgres:16.4
    container_name: postgres_16_4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  issue_script:
    build:
      context: .
      dockerfile: Dockerfile.issue_script
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    depends_on:
      - postgres

volumes:
  postgres_data:
