default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  port: 5433
  host: localhost

default_collate_c: &default_collate_c
  <<: *default
  template: template0
  collation: C
  ctype: C

development:
  primary:
    <<: *default
    database: default_development
  collate_c:
    <<: *default_collate_c
    database: collate_c_development

test:
  primary:
    <<: *default
    database: default_test
  collate_c:
    <<: *default_collate_c
    database: collate_c_test
